"""create job postings

Revision ID: 6ac022492f81
Revises: dba656f9805e
Create Date: 2026-08-06 20:21:46.071513
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "6ac022492f81"
down_revision: str | None = "dba656f9805e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint(
        "target_role_recruitment_stage",
        "target_roles",
        "recruitment_stage IN ('daily_internship', 'summer_internship', "
        "'winter_internship', 'autumn_recruitment', 'spring_recruitment', 'other')",
    )
    op.create_table(
        "job_postings",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("target_role_id", sa.Uuid(), nullable=False),
        sa.Column("company_name", sa.String(length=100), nullable=False),
        sa.Column("job_title", sa.String(length=150), nullable=False),
        sa.Column(
            "recruitment_stage",
            sa.Enum(
                "daily_internship",
                "summer_internship",
                "winter_internship",
                "autumn_recruitment",
                "spring_recruitment",
                "other",
                name="job_posting_recruitment_stage",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("city", sa.String(length=100), nullable=True),
        sa.Column("source_url", sa.String(length=2048), nullable=True),
        sa.Column("original_text", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "draft",
                "queued",
                "extracting",
                "analyzing",
                "review_required",
                "confirmed",
                "failed",
                name="job_posting_status",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("collected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["target_role_id"], ["target_roles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_job_postings_target_role_id"), "job_postings", ["target_role_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_job_postings_target_role_id"), table_name="job_postings")
    op.drop_table("job_postings")
    op.drop_constraint(
        "target_role_recruitment_stage",
        "target_roles",
        type_="check",
    )
    # ### end Alembic commands ###
