"""create target roles

Revision ID: dba656f9805e
Revises:
Create Date: 2026-08-06 20:10:34.160610
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "dba656f9805e"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "target_roles",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column(
            "recruitment_stage",
            sa.Enum(
                "daily_internship",
                "summer_internship",
                "winter_internship",
                "autumn_recruitment",
                "spring_recruitment",
                "other",
                name="target_role_recruitment_stage",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_target_roles_created_at"), "target_roles", ["created_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_target_roles_created_at"), table_name="target_roles")
    op.drop_table("target_roles")
    # ### end Alembic commands ###
